### ISSUE TITLE
What projects should appear in the "Grooming" column?

### ISSUE THREAD

**Issue by nilsberg** [AlexanderWillner/KanbanView#7]
> @AlexanderWillner wrote:
> I added a new column to show empty projects.

I really like the "Grooming" column!
For me it would be useful, if "stalled" projects are shown in the grooming column.
I (and many others) define a *stalled project* as a project that does not have a next action. Now we need to clarify the next action. For me, a *next action* is a task that is not scheduled for Someday, i.e. it is either available now or scheduled for a specific date.

> @AlexanderWillner wrote:
> actually, this is on purpose: imho the project should be scheduled when there is no active task anymore (but only scheduled ones)

This is personal preference. I do not flesh out all tasks of a project. So a project can be active (i.e. if I have time, I take a look at it) without having a task written down that I can do right now.
It is stalled if it has neither an unscheduled or Upcoming task, as nothing will happen if I just look at my tasks. In contrast, a project with an Upcoming task will eventually get moved forward, when the scheduled task appears in my today view.

To filter out projects that have a scheduled task, I added the disjunct `OR PROJECT_TASK.{self.IS_SCHEDULED}` to the counting part of the "Grooming" query (actually the function is called `get_empty_projects` ;) ).

This still leaves me with projects, that have recurring tasks in them. I do not want to see those projects in "grooming", as they also get moved forward (and usually are maintenance projects).
When not counting recurring tasks, one needs to be aware of paused recurring tasks and ended recurring tasks, as both are not next tasks according to my and your definition.

I have another disjunct for the counting part in the "Grooming" query to filter recurring tasks that are neither paused nor ended.

``` python
RECURRING_IS_NOT_PAUSED = "instanceCreationPaused = 0"
RECURRING_HAS_NEXT_STARTDATE = "nextInstanceStartDate IS NOT NULL"

... OR 
(PROJECT_TASK.{self.IS_RECURRING} AND 
PROJECT_TASK.{self.RECURRING_IS_NOT_PAUSED} AND
PROJECT_TASK.{self.RECURRING_HAS_NEXT_STARTDATE})
```

edit: exclude recurring tasks that are ended.

**Comment by AlexanderWillner** [comment]
I massively refactored the code. Would you mind looking at the current function again and propose how to extend it?

**Comment by lucbeaulieu** [comment]
Will try and come back to you!

**Comment by lucbeaulieu** [comment]
Still not clear what project appears in the grooming column. For example, I have a few projects for which my next tasks are a future actions - either recurring or planned (for example to remind me to plan a meeting with students for general purpose: how the overall PhD project is going, plan for some personnal development  training, ...):  some of these project appears in Upcoming but others in Grooming?

I also see for of my maintenance projects (with recurring tasks) in Grooming while no action needs to be taken at all. 

For the Backlog: this correspond to Task/Or projects in the Someday box of Things. These are really Backburner rather than Backlog (backburner definition: postpone consideration of or action on.)

With the new interface I think I can do everything I had before with my previous KanbanView (or the modified V2.3 see picture below), just need to go over a few Kanban (and adapt my tag e.g. WaitingFor-> Waiting, get use to MIT or Cleanup. 

 One thing to consider, that some might not find obvious: when looking at Project Kanban, the toggle shows T (but hide P) and when looking at task-based Kanban, the toggle shows P (but hide T). I wonder if both T and P should not be visible at all time but the visual cue could be a push-in effect? 

[Capture d’écran, le 2020-04-21 à 16.58.45.pdf](https://github.com/AlexanderWillner/KanbanView/files/4512641/Capture.d.ecran.le.2020-04-21.a.16.58.45.pdf)

[Capture d’écran, le 2020-04-21 à 16.59.29.pdf](https://github.com/AlexanderWillner/KanbanView/files/4512642/Capture.d.ecran.le.2020-04-21.a.16.59.29.pdf)

**Comment by nilsberg** [comment]
> @AlexanderWillner wrote:
> I massively refactored the code. Would you mind looking at the current function again and propose how to extend it?

Of course! I'll paste and explain here. If you prefer a PR, just say so. I will now stop saying this.

```python
class Things3():

    ...

    # Extend the SQL mini language
    RECURRING_IS_NOT_PAUSED = "instanceCreationPaused = 0"
    RECURRING_HAS_NEXT_STARTDATE = "nextInstanceStartDate IS NOT NULL"

    ...

    def get_empty_projects(self):
        """Get projects that are empty"""
        query = f"""
            TASK.{self.IS_NOT_TRASHED} AND
            TASK.{self.IS_OPEN} AND
            TASK.{self.IS_PROJECT} AND
            TASK.{self.IS_ANYTIME}  # removed IS_SCHEDULED here [1]
            GROUP BY TASK.uuid
            HAVING
                (SELECT COUNT(uuid)
                 FROM TMTask AS PROJECT_TASK
                 WHERE
                   PROJECT_TASK.project = TASK.uuid AND
                   PROJECT_TASK.{self.IS_NOT_TRASHED} AND
                   PROJECT_TASK.{self.IS_OPEN} AND
                    # count also scheduled tasks [2]
                   (PROJECT_TASK.{self.IS_ANYTIME} OR PROJECT_TASK.{self.IS_SCHEDULED} OR
                       # count recurring tasks that are neither paused nor ended [3]
                      (PROJECT_TASK.{self.IS_RECURRING} AND
                       PROJECT_TASK.{self.RECURRING_IS_NOT_PAUSED} AND
                       PROJECT_TASK.{self.RECURRING_HAS_NEXT_STARTDATE}
                      )
                   )
                ) = 0
            """
        return self.get_rows(query)
```

[1]: Personal preference. When a project is scheduled, it will appear in my Today view, so I do not consider it stalled.

[2]: Personal preference. When a project contains scheduled items, I do not consider it stalled.

[3]: Similar to the previous one, as repeating tasks are also scheduled. One needs to make sure to not consider paused nor ended repeating tasks, as those do not count as next actions.

**Comment by AlexanderWillner** [comment]
@nilsberg Thanks! I created a specific branch to fixing this bigger issue (what exactly should be shown in the grooming section?)

**Comment by AlexanderWillner** [comment]
@lucbeaulieu regarding your comments

> Still not clear what project appears in the grooming column. 

yes, we're now streamlining this in another branch. Maybe 

> For example, I have a few projects for which my next tasks are a future actions - either recurring or planned (for example to remind me to plan a meeting with students for general purpose: how the overall PhD project is going, plan for some personnal development training, ...): some of these project appears in Upcoming but others in Grooming?
...
> I also see for of my maintenance projects (with recurring tasks) in Grooming while no action needs to be taken at all.

The next fixes from @nilsberg might have fixed that. Otherwise let's extend the query till we're happy.

> For the Backlog: this correspond to Task/Or projects in the Someday box of Things. These are really Backburner rather than Backlog (backburner definition: postpone consideration of or action on.)

Imho the "Backlog" in Kanban/Scrum relates to the "Someday" area in GTD.

> With the new interface I think I can do everything I had before with my previous KanbanView (or the modified V2.3 see picture below), just need to go over a few Kanban (and adapt my tag e.g. WaitingFor-> Waiting, get use to MIT or Cleanup.

You can now configure the tags in `~/.kanbanviewrc`, however, it's not documented yet.

> One thing to consider, that some might not find obvious: when looking at Project Kanban, the toggle shows T (but hide P) and when looking at task-based Kanban, the toggle shows P (but hide T). I wonder if both T and P should not be visible at all time but the visual cue could be a push-in effect?

Might have been a glitch. I updated also a few things. "T" is visible in task mode and "P" is visible in project mode.

**Comment by nilsberg** [comment]
The behavior in the branch `fix-grooming` is as I expect it. Thank you.
Projects that are lint (without area) and are 'empty' (have no next action) appear twice in the grooming column.

I agree to the backlog should be someday. Otherwise a tag should be used.

**Comment by lucbeaulieu** [comment]
Still unsure. Here is below an example of a project in Things (jpg file) in which there is a task with a due Date in the future. It appears own Grooming instead of Upcoming?

![Capture d’écran, le 2020-04-22 à 11 52 02](https://user-images.githubusercontent.com/42723447/80004450-5423a280-8490-11ea-86c4-fc6eb8f59b52.jpg)

**Comment by nilsberg** [comment]
@lucbeaulieu Is the project part of an area?

**Comment by lucbeaulieu** [comment]
It works now. I do see one remaining issue: tasks that are scheduled for a given date, do appear in Upcoming but the date is not displayed.
